### ISSUE TITLE
Don't include your .env file in git

### ISSUE THREAD

**Issue by jtuppy** [zsiskos/recipe-app#3]
https://github.com/zsiskos/recipe-app/blob/fae17dc7334ccaa54df38058217be04a04b63f04/.env#L1-L3

Make sure it is in .gitignore... It is always a good idea to ignore the .env file from git, especially if the repo is public. This is especially important since you had your production database uri in that file. The username and password to your database has now been exposed to anyone who looks at this repo. I would advice that you change the database/password/ and username because it is compromised now

**Comment by zsiskos** [comment]
My .gitignore wasn't in my root folder, which is why it didn't ignore it. Good lesson to learn now! :) Thanks!
